### ISSUE TITLE
Log level fatal is not supported

### ISSUE THREAD

**Issue by slntopp** [tomMoulard/zap-slog#7]
Hi there, sweet package, was testing it and stumbled upon this issue. 

I have an app based on echo, which used slog and a module i'm trying to hook up with it, which is using zap. That module tho can throw `fatal`s sometimes, which is expected. Tho the wrapper returns the following:
App still crashes as expected anyhow, but the log turns out to be less informative.

```
2024/08/28 18:40:41 WARN Failed to unmarshal log level level=fatal error="slog: level string \"fatal\": unknown name"
```

**Comment by tomMoulard** [comment]
Indeed, this is because I thought [this](https://github.com/tomMoulard/zap-slog/blob/0021b404f64846321da0e95c5b4c84e5013c8498/slog.go#L30-L35) would do the trick but no luck. I'm removing that ASAP.
Thanks for the catch !

**Comment by tomMoulard** [comment]
I tried to fix this issue with https://github.com/tomMoulard/zap-slog/commit/f5da5ad302de381ab12e8f042356d7cb81bfaf4d. Can you try with this version, and tell me if this fixes yout issue.
Thanks !

**Comment by slntopp** [comment]
That has fixed the issue, thanks @tomMoulard !
